package com.quantfund.api.service;

import com.quantfund.common.entity.*;
import com.quantfund.common.repository.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.util.*;

/**
 * 报告导出服务 —— HTML报告 / CSV交易日志 / JSON指标数据
 */
@Service
public class ExportService {

    @Autowired private BacktestRunRepository runRepo;
    @Autowired private BacktestResultRepository resultRepo;
    @Autowired private FundRepository fundRepo;

    /**
     * 生成回测HTML报告
     */
    public String generateBacktestReport(Long backtestId) {
        BacktestRun run = runRepo.findById(backtestId).orElse(null);
        BacktestResult result = resultRepo.findByBacktestId(backtestId).orElse(null);
        if (run == null || result == null) return "<html><body>报告不存在</body></html>";

        StringBuilder html = new StringBuilder();
        html.append("""
                <!DOCTYPE html><html><head><meta charset="UTF-8">
                <title>回测报告</title>
                <style>body{font-family:Arial;max-width:900px;margin:0 auto;padding:20px;}
                .metric{display:inline-block;margin:10px 20px 10px 0;padding:12px;border:1px solid #ddd;border-radius:8px;}
                .metric .value{font-size:24px;font-weight:bold;}
                .metric .label{font-size:12px;color:#666;}
                table{border-collapse:collapse;width:100%;margin-top:20px;}
                th,td{border:1px solid #ddd;padding:8px;text-align:right;}
                th{background:#f5f5f5;}
                .positive{color:#67c23a}.negative{color:#f56c6c}
                </style></head><body>
                """);

        html.append("<h1>策略回测报告</h1>");
        html.append("<p>回测ID: ").append(backtestId)
            .append(" | 区间: ").append(run.getStartDate()).append(" ~ ").append(run.getEndDate())
            .append(" | 初始资金: ¥").append(String.format("%,.0f", run.getInitialCapital()))
            .append("</p>");

        // 核心指标
        html.append("<div>");
        metricCard(html, "总收益率", fmtPct(result.getTotalReturn()));
        metricCard(html, "年化收益", fmtPct(result.getAnnualReturn()));
        metricCard(html, "夏普比率", fmtNum(result.getSharpeRatio()));
        metricCard(html, "最大回撤", fmtPct(result.getMaxDrawdown()));
        metricCard(html, "Sortino", fmtNum(result.getSortinoRatio()));
        metricCard(html, "Calmar", fmtNum(result.getCalmarRatio()));
        metricCard(html, "波动率", fmtPct(result.getVolatility()));
        metricCard(html, "胜率", fmtPct(result.getWinRate()));
        metricCard(html, "交易次数", String.valueOf(result.getTotalTrades()));
        html.append("</div><hr>");

        // 交易记录表
        if (result.getTradeLog() != null) {
            html.append("<h2>交易记录</h2>");
            html.append("<table><tr><th>日期</th><th>基金</th><th>方向</th>")
                .append("<th>份额</th><th>价格</th><th>金额</th><th>手续费</th><th>理由</th></tr>");
            try {
                var trades = new com.fasterxml.jackson.databind.ObjectMapper()
                        .readValue(result.getTradeLog(), List.class);
                for (var t : trades) {
                    Map<String, Object> tr = (Map<String, Object>) t;
                    html.append("<tr>")
                        .append("<td>").append(tr.get("date")).append("</td>")
                        .append("<td>").append(tr.get("fundCode")).append("</td>")
                        .append("<td class='").append("BUY".equals(tr.get("type")) ? "positive" : "negative")
                        .append("'>").append(tr.get("type")).append("</td>")
                        .append("<td>").append(tr.get("shares")).append("</td>")
                        .append("<td>").append(tr.get("price")).append("</td>")
                        .append("<td>").append(tr.get("amount")).append("</td>")
                        .append("<td>").append(tr.get("fee")).append("</td>")
                        .append("<td>").append(tr.get("reason")).append("</td>")
                        .append("</tr>");
                }
            } catch (Exception e) { html.append("<tr><td colspan='8'>解析交易记录失败</td></tr>"); }
            html.append("</table>");
        }

        html.append("<hr><p style='color:#999;font-size:12px;'>Generated by China Quant Fund Platform on ")
            .append(LocalDate.now()).append("</p>");
        html.append("</body></html>");
        return html.toString();
    }

    /**
     * 导出CSV交易日志
     */
    public String exportTradeCsv(Long backtestId) {
        BacktestResult result = resultRepo.findByBacktestId(backtestId).orElse(null);
        if (result == null || result.getTradeLog() == null) return "date,fundCode,type,shares,price,amount,fee,reason";

        StringBuilder csv = new StringBuilder("date,fundCode,type,shares,price,amount,fee,reason\n");
        try {
            var trades = new com.fasterxml.jackson.databind.ObjectMapper()
                    .readValue(result.getTradeLog(), List.class);
            for (var t : trades) {
                Map<String, Object> tr = (Map<String, Object>) t;
                csv.append(String.format("%s,%s,%s,%.4f,%.4f,%.2f,%.2f,%s\n",
                        tr.get("date"), tr.get("fundCode"), tr.get("type"),
                        ((Number) tr.get("shares")).doubleValue(),
                        ((Number) tr.get("price")).doubleValue(),
                        ((Number) tr.get("amount")).doubleValue(),
                        ((Number) tr.get("fee")).doubleValue(),
                        tr.get("reason")));
            }
        } catch (Exception e) { /* */ }
        return csv.toString();
    }

    private void metricCard(StringBuilder sb, String label, String value) {
        sb.append("<div class='metric'><div class='value'>").append(value)
          .append("</div><div class='label'>").append(label).append("</div></div>");
    }

    private String fmtPct(java.math.BigDecimal v) {
        if (v == null) return "-";
        return String.format("%+.2f%%", v.doubleValue() * 100);
    }
    private String fmtNum(java.math.BigDecimal v) {
        if (v == null) return "-";
        return String.format("%.3f", v.doubleValue());
    }
}
